//
// BasicStationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct BasicStationInfo: Codable {

    public var id: Int?
    public var latitude: Double?
    public var longitude: Double?
    public var name: String?
    public var city: String?
    public var address: String?
    public var provider: String?
    public var evses: [Connector]?
    public var icon: Int?
    public var isRemoved: Bool?
    public var isPrivate: Bool?

    public init(id: Int?, latitude: Double?, longitude: Double?, name: String?, city: String?, address: String?, provider: String?, evses: [Connector]?, icon: Int?, isRemoved: Bool?, isPrivate: Bool?) {
        self.id = id
        self.latitude = latitude
        self.longitude = longitude
        self.name = name
        self.city = city
        self.address = address
        self.provider = provider
        self.evses = evses
        self.icon = icon
        self.isRemoved = isRemoved
        self.isPrivate = isPrivate
    }


}

