//
// ConnectorType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public enum ConnectorType: String, Codable {
    case ccs = "CCS"
    case chademo = "CHAdeMO"
    case type2 = "Type2"
    case type3 = "Type3"
    case shuko = "Shuko"
}
