//
// Connector.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Connector: Codable {

    public enum CurrentType: String, Codable {
        case ac = "AC"
        case dc = "DC"
    }
    /** Id of the specific connector */
    public var connectorID: Int?
    public var type: ConnectorType?
    public var currentType: CurrentType?
    /** Maximum power of specific connector */
    public var maxKw: Double?

    public init(connectorID: Int?, type: ConnectorType?, currentType: CurrentType?, maxKw: Double?) {
        self.connectorID = connectorID
        self.type = type
        self.currentType = currentType
        self.maxKw = maxKw
    }


}

