//
// EVSE.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EVSE: Codable {

    public var id: Int?
    public var connectors: [Connector]?
    /** Whether this EVSE is available for usage */
    public var available: Bool?
    /** Whether this EVSE is available for reservation */
    public var reservable: Bool?
    public var pricing: [Pricing]?
    /** Currently GET stations/{id} uses this field. Won&#39;t be added in that endpoint for Hubject stations. */
    public var oneTimePayment: Bool?
    public var status: Int?
    public var minutesWithoutTimeCharge: Int?

    public init(id: Int?, connectors: [Connector]?, available: Bool?, reservable: Bool?, pricing: [Pricing]?, oneTimePayment: Bool?, status: Int?, minutesWithoutTimeCharge: Int?) {
        self.id = id
        self.connectors = connectors
        self.available = available
        self.reservable = reservable
        self.pricing = pricing
        self.oneTimePayment = oneTimePayment
        self.status = status
        self.minutesWithoutTimeCharge = minutesWithoutTimeCharge
    }


}

