//
// InlineResponse404.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse404: Codable {

    public var statusCode: Int?
    public var message: String?

    public init(statusCode: Int?, message: String?) {
        self.statusCode = statusCode
        self.message = message
    }

    public enum CodingKeys: String, CodingKey { 
        case statusCode = "status_code"
        case message
    }


}

