//
// InlineResponse200.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse200: Codable {

    public var token: String?

    public init(token: String?) {
        self.token = token
    }


}

