//
// InlineObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineObject: Codable {

    /** End-users email address */
    public var email: String
    /** End-users password code */
    public var code: String

    public init(email: String, code: String) {
        self.email = email
        self.code = code
    }


}

