//
// InlineResponse2001.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct InlineResponse2001: Codable {

    public var status: String?
    public var message: String?

    public init(status: String?, message: String?) {
        self.status = status
        self.message = message
    }


}

