//
// Pricing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Pricing: Codable {

    /** Translation key for the price name */
    public var name: String?
    public var priceCents: Double?
    public var currency: String?
    /** a field to express pricing related time. For example, name - first free time, minutes - 666 to say that first 666 minutes a user will not be charged a time based fee. */
    public var minutes: Int?

    public init(name: String?, priceCents: Double?, currency: String?, minutes: Int?) {
        self.name = name
        self.priceCents = priceCents
        self.currency = currency
        self.minutes = minutes
    }


}

