name: VirtaSdk
targets:
  VirtaSdk:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [VirtaSdk]
    info:
      path: ./Info.plist
      version: 4.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: Alamofire
